language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
script:
  - tox
notifications:
  email:
    recipients:
      - wangbinxin001@126.com
      - agnewee@gmail.com
      - xzg.nju@gmail.com
    on_success: always
    on_failure: always
